name: accelerator-env
channels:
  - conda-forge
dependencies:
  - just
  - libprotobuf<6
  - verilator>=5
  - python>=3.9,<3.11
  - pip
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - deepdiff
      - huggingface-hub==1.24.0
      - xonsh
      - prompt_toolkit==3.0.53
      - openpyxl
      - git+https://github.com/allpan3/mflowgen.git@8914a6d9cd67430ed61914a6b8ae11a14a60f61f#egg=mflowgen
      - pandas
      - compiledb
      - -e voyager-compiler
      - -e interstellar
variables:
  CODEGEN_DIR: test/compiler
