# Read and set relevant environment variables
set ENV_VARS {BLOCK CLOCK_PERIOD DATATYPE IC_DIMENSION OC_DIMENSION INPUT_BUFFER_SIZE WEIGHT_BUFFER_SIZE ACCUM_BUFFER_SIZE TECHNOLOGY CATAPULT_BUILD_DIR DOUBLE_BUFFERED_ACCUM_BUFFER SUPPORT_MVM SUPPORT_SPMM SUPPORT_DWC MATRIX_BACKEND CIM_CH_IN CIM_CH_OUT CIM_B_SETS CIM_BASE_A_WIDTH CIM_BASE_B_WIDTH CIM_BASE_C_WIDTH CIM_WRITE_CH_IN CIM_MAC_LATENCY CIM_MODE CIM_TILE_INPUT_LANES CIM_TILE_OUTPUT_LANES CIM_REDUCTION_GROUPS CIM_MULTICAST_GROUPS CIM_C_PORT_ORIENTATION}

foreach var $ENV_VARS {
  set $var [exec echo $::env($var)]
}

set ROOT [file normalize $::env(PROJ_ROOT)]
