#!/usr/bin/env python3
"""Generate CIMElement SystemC/RTL co-simulation case glue."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

MODE_PARALLEL = 0
MODE_SERIAL = 1


# One immutable CIMElement co-simulation parameter set
@dataclass(frozen=True)
class Case:
    name: str
    prefix: str
    k: int
    n: int
    b_sets: int
    base_a_width: int
    base_b_width: int
    base_c_width: int
    bk: int
    mac_latency: int
    mode: int
    a_width: int
    b_width: int
    signed: bool


CASES = (
    Case(
        name="unsigned_parallel",
        prefix="VCIMElementCosimUnsignedParallel",
        k=4,
        n=2,
        b_sets=2,
        base_a_width=4,
        base_b_width=4,
        base_c_width=10,
        bk=2,
        mac_latency=1,
        mode=MODE_PARALLEL,
        a_width=4,
        b_width=4,
        signed=False,
    ),
    Case(
        name="signed_serial",
        prefix="VCIMElementCosimSignedSerial",
        k=4,
        n=2,
        b_sets=2,
        base_a_width=4,
        base_b_width=4,
        base_c_width=20,
        bk=1,
        mac_latency=2,
        mode=MODE_SERIAL,
        a_width=8,
        b_width=8,
        signed=True,
    ),
    Case(
        name="signed_wide_b_parallel",
        prefix="VCIMElementCosimSignedWideBParallel",
        k=5,
        n=2,
        b_sets=3,
        base_a_width=4,
        base_b_width=4,
        base_c_width=12,
        bk=1,
        mac_latency=3,
        mode=MODE_PARALLEL,
        a_width=5,
        b_width=8,
        signed=True,
    ),
)


# Return the number of physical macro output channels required by one case
def ch_out(case: Case) -> int:
    return case.n * (case.b_width // case.base_b_width)


# Return one shell-safe Verilator parameter assignment list
def verilator_params(case: Case) -> str:
    return " ".join(
        [
            f"-GCH_IN={case.k}",
            f"-GCH_OUT={ch_out(case)}",
            f"-GB_SETS={case.b_sets}",
            f"-GBASE_A_WIDTH={case.base_a_width}",
            f"-GBASE_B_WIDTH={case.base_b_width}",
            f"-GBASE_C_WIDTH={case.base_c_width}",
            f"-GWRITE_CH_IN={case.bk}",
            f"-GMAC_LATENCY={case.mac_latency}",
            f"-GMODE={case.mode}",
            f"-GA_WIDTH={case.a_width}",
            f"-GB_WIDTH={case.b_width}",
            f"-GSIGNED={int(case.signed)}",
        ]
    )


# Write the C++ include consumed by CIMElementTb.cc
def write_cpp_include(path: Path) -> None:
    lines = [
        "// Generated by test/unittest/systemc/cim_element_cosim_cases.py",
        "#pragma once",
        "",
    ]

    for case in CASES:
        lines.append(f'#include "{case.prefix}.h"')

    for case in CASES:
        signed_literal = "true" if case.signed else "false"
        lines.extend(
            [
                "",
                f"// Instantiate the generated {case.name} co-simulation case",
                f"static void instantiate_{case.name}() {{",
                f"  static CIMElementTbCase<{case.prefix}, "
                f"{case.k}, {case.n}, {case.b_sets}, "
                f"{case.base_a_width}, {case.base_b_width}, "
                f"{case.base_c_width}, {case.bk}, "
                f"{case.mac_latency}, {case.mode}, {case.a_width}, "
                f"{case.b_width}, {signed_literal}>",
                f'      {case.name}("{case.name}");',
                "}",
            ]
        )

    lines.extend(
        [
            "",
            "static constexpr int kCIMElementTbCaseCount = "
            f"{len(CASES)};",
            "static constexpr CIMElementTbCaseDescriptor "
            "kCIMElementTbCases[] = {",
        ]
    )

    for case in CASES:
        lines.append(f'    {{"{case.name}", instantiate_{case.name}}},')

    lines.append("};")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


# Write the Makefile fragment consumed by test/unittest/Makefile
def write_makefile(path: Path) -> None:
    libs = [
        f"$(CIM_VERILATED_DIR)/{case.name}/{case.prefix}__ALL.a"
        for case in CASES
    ]
    include_flags = [
        f"-I$(CIM_VERILATED_DIR)/{case.name}"
        for case in CASES
    ]

    lines = [
        "# Generated by test/unittest/systemc/cim_element_cosim_cases.py",
        "",
        "CIM_ELEMENT_VERILATED_LIBS := \\",
    ]

    for index, lib in enumerate(libs):
        suffix = " \\" if index != len(libs) - 1 else ""
        lines.append(f"\t{lib}{suffix}")

    lines.extend(
        [
            f"CIM_ELEMENT_VERILATED_RUNTIME_LIB := {libs[0].rsplit('/', 1)[0]}/libverilated.a",
            "CIM_ELEMENT_VERILATED_INCLUDE_FLAGS := \\",
        ]
    )

    for index, include_flag in enumerate(include_flags):
        suffix = " \\" if index != len(include_flags) - 1 else ""
        lines.append(f"\t{include_flag}{suffix}")

    lines.extend(
        [
            "",
            "$(SYSTEMC_CASES_INC): $(SYSTEMC_CASES)",
            "\tmkdir -p $(SYSTEMC_GENERATED)",
            "\t$(PYTHON) $(SYSTEMC_CASES) --cpp-include $@",
            "",
        ]
    )

    for case, lib in zip(CASES, libs):
        case_dir = f"$(CIM_VERILATED_DIR)/{case.name}"
        lines.extend(
            [
                f"{lib}: $(CIM_RTL_SRCS)",
                f"\tmkdir -p {case_dir}",
                f"\t$(VERILATOR) -sv --cc -I$(REPO_ROOT)/src/CIM $(CIM_RTL_SRCS) "
                f"--top-module CIMIntElementPacked --prefix {case.prefix} "
                f"--Mdir {case_dir} {verilator_params(case)}",
                f"\t$(MAKE) -C {case_dir} -f {case.prefix}.mk CXX=$(SYSTEMC_CC)",
                "",
            ]
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


# Parse command-line output selection
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp-include", type=Path)
    parser.add_argument("--makefile", type=Path)
    return parser.parse_args()


# Generate the requested build artifacts
def main() -> None:
    args = parse_args()
    if args.cpp_include is None and args.makefile is None:
        raise SystemExit("one of --cpp-include or --makefile is required")
    if args.cpp_include is not None:
        write_cpp_include(args.cpp_include)
    if args.makefile is not None:
        write_makefile(args.makefile)


if __name__ == "__main__":
    main()
