# Catapult block definition for the CIMArray tile grid

set block "CIMArray"
set full_block_name "CIMArray<$CIM_CH_IN, $CIM_CH_OUT, $CIM_B_SETS, $CIM_BASE_A_WIDTH, $CIM_BASE_B_WIDTH, $CIM_BASE_C_WIDTH, $CIM_WRITE_CH_IN, $CIM_MAC_LATENCY, $CIM_MODE, $INPUT_DTYPE_WIDTH, $WEIGHT_DTYPE_WIDTH, $ACCUM_DATATYPE_WIDTH, $CIM_SIGNED, $CIM_TILE_INPUT_AXIS_ELEMENTS, $CIM_TILE_OUTPUT_AXIS_ELEMENTS, $CIM_INPUT_AXIS_TILES, $CIM_OUTPUT_AXIS_TILES, $CIM_A_PORT_TILES, $CIM_B_PORT_TILES, $CIM_C_PORT_TILES, $CIM_C_BEAT_LAYOUT, $CIM_ARRAY_RESULT_SLOTS_PER_OUTPUT_LANE>"
